modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="chuck_craft"
version="1.0.0"
displayName="Chuck Craft"
displayURL="https://github.com/airpioa/Chuck-Craft"
logoFile="logo.png"
credits="The Chuck Team"
authors="Airpioa"
description="A project for porting chuck to minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.chuck_craft]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chuck_craft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration